### ISSUE TITLE
Can't Create new project by github api limit.

### ISSUE THREAD

**Issue by kk2170** [MasoniteFramework/craft#19]
## Description
I can't create a new project with craft command.

```
$ craft new myproject
  [ProjectLimitReached]
  You have reached your hourly limit of creating new projects. Try again in 1 hour.
```

## suggest to fix
I want to use my access token on github.
so please make a option or load environment variables.

**Comment by josephmancuso** [comment]
the actual way to fix this would be to have a dedicated server to handle this but can't really afford it at this moment. This one would a good temporary fix though.

You did create a few projects within an hour right? I was always afraid that it would be on a global scale rather than a per IP address scale but i'm pretty sure it's per IP address

**Comment by rfschubert** [comment]
@josephmancuso how much an dedicated server costs?

**Comment by josephmancuso** [comment]
@rfschubert depends on where it's hosted. If it's heroku which has all that autoscale functionality it'll be pretty expensive, prob $75 /mo ($25 for a standard server plus $50 for a database to house more than the 10,000 rows under the $7 plan.)

If i can get a project I'm working on up I can host it on a dedicated server for maybe $15 per month but without any bells and whistles. Just a plain server setup

**Comment by josephmancuso** [comment]
actually Heroku will be more like ~$35/mo
