### ISSUE TITLE
TypeError: 'module' object is not callable

### ISSUE THREAD

**Issue by nioperas06** [MasoniteFramework/craft#8]
Just trying to follow package creation wiki. I create InstallCommand and when run `craft` I have this error 😕.
```
WARNING: 'module' object is not callable
Traceback (most recent call last):  File "/Users/nioperas06/.local/share/virtualenvs/masonite-package-J5jd90TB/bin/craft", line 7, in <module>    from masonite_cli.application import application  File "/Users/nioperas06/.local/share/virtualenvs/masonite-package-J5jd90TB/lib/python3.6/site-packages/masonite_cli/application.py", line 39, in <module>
    from wsgi import container
  File "/Users/nioperas06/workspace/tutorials/masonite-package/tuto/wsgi.py", line 42, in <module>
    located_provider.load_app(container).register()
  File "/Users/nioperas06/workspace/tutorials/masonite-package/tuto/app/providers/InstallProvider.py", line 10, in register
    self.app.bind('InstallCommand', InstallCommand())
TypeError: 'module' object is not callable
```

- InstallCommand.py
```
""" A InstallCommand Command """
from cleo import Command


class InstallCommand(Command):

    def handle(self):
        pass
```

- InstallProvider.py
```
''' A InstallProvider Service Provider '''
from masonite.provider import ServiceProvider
from app.commands import InstallCommand

class InstallProvider(ServiceProvider):

    wsgi = False

    def register(self):
        self.app.bind('InstallCommand', InstallCommand())

    def boot(self):
        pass
```

- config/providers.py
```
...
from app.providers.InstallProvider import InstallProvider
...
PROVIDERS = [
    ...
    InstallProvider,
]
```
😕

**Comment by josephmancuso** [comment]
`from app.commands.InstallCommand import InstallCommand`

**Comment by josephmancuso** [comment]
Since `InstallCommand` is a module. You'll need to create an `__init__.py` file inside the `app.commands` directory and do something like `.InstallCommand import InstallCommand` if you want to just do `from app.commands import InstallCommand`

**Comment by nioperas06** [comment]
Makes sense. Just that it's weird to follow the wiki and to encounter an error 😁. Closed!

**Comment by josephmancuso** [comment]
woops :) fixed

**Comment by cronywalls** [comment]
This error statement TypeError: ['module' object is not callable](http://net-informations.com/python/iq/typeerror.htm) is raised as you are being confused about the Class name and Module name. The problem is in the import line . You are importing a module, not a class. This happend because the module name and class name have the same name .

If you have a class "MyClass" in a file called "MyClass.py" , then you should import :
 
from MyClass import MyClass

In Python , a script is a module, whose name is determined by the filename . So when you start out your file MyClass.py with import MyClass you are creating a loop in the module structure.
